/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataflow;

import Beans.CanvasPanel;
import Beans.NewTab;
import Canvas.Shapes;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
//import Canvas.FrameTest;
//import static Canvas.FrameTest.MainFrame;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Set;
import java.util.Stack;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Shreyas
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        tabs=new ArrayList<>();
        tabs.add(newTab1);
        setCodeFont();
        codeComp = new CodeCompiler(this);
        //codeTextArea1.setFont(fontSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        toolBar1 = new Beans.ToolBar();
        jPanel4 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        fileTabPane = new javax.swing.JTabbedPane();
        newTab1 = new Beans.NewTab();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        itemOpen = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        itemSaveAsPNG = new javax.swing.JMenuItem();
        itemExportCode = new javax.swing.JMenuItem();
        itemClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        incFontSize = new javax.swing.JMenuItem();
        decFontSize = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemDrawLine = new javax.swing.JMenuItem();
        itemDragObj = new javax.swing.JMenuItem();
        radioItemSelect = new javax.swing.JRadioButtonMenuItem();
        radioItemMove = new javax.swing.JRadioButtonMenuItem();
        radioItemJoin = new javax.swing.JRadioButtonMenuItem();
        radioItemAdd = new javax.swing.JRadioButtonMenuItem();
        radioItemDelete = new javax.swing.JRadioButtonMenuItem();
        radioItemDeleteLine = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        itemGenCode = new javax.swing.JMenuItem();
        itemAutoForm = new javax.swing.JMenuItem();
        itemCodeSave = new javax.swing.JMenuItem();
        itemCompile = new javax.swing.JMenuItem();
        itemRun = new javax.swing.JMenuItem();
        itemStop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setResizeWeight(1.0);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 514));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setMinimumSize(new java.awt.Dimension(100, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(298, 300));

        javax.swing.GroupLayout toolBar1Layout = new javax.swing.GroupLayout(toolBar1);
        toolBar1.setLayout(toolBar1Layout);
        toolBar1Layout.setHorizontalGroup(
            toolBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        toolBar1Layout.setVerticalGroup(
            toolBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(298, 200));

        progressBar.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(800, 100));

        fileTabPane.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        fileTabPane.addTab("Tab 1", newTab1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 514, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itemNew.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        itemNew.setText("New");
        itemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewActionPerformed(evt);
            }
        });
        jMenu1.add(itemNew);

        itemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemOpen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open.png"))); // NOI18N
        itemOpen.setText("Open");
        jMenu1.add(itemOpen);

        itemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSave.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        itemSave.setText("Save");
        jMenu1.add(itemSave);

        itemSaveAsPNG.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemSaveAsPNG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemSaveAsPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saveAs.png"))); // NOI18N
        itemSaveAsPNG.setText("Save as PNG");
        itemSaveAsPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveAsPNGActionPerformed(evt);
            }
        });
        jMenu1.add(itemSaveAsPNG);

        itemExportCode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemExportCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectAll.png"))); // NOI18N
        itemExportCode.setText("Export Code");
        jMenu1.add(itemExportCode);

        itemClose.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        itemClose.setText("Close");
        jMenu1.add(itemClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        incFontSize.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        incFontSize.setText("A +");
        incFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incFontSizeActionPerformed(evt);
            }
        });
        jMenu2.add(incFontSize);

        decFontSize.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        decFontSize.setText("A -");
        decFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFontSizeActionPerformed(evt);
            }
        });
        jMenu2.add(decFontSize);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Tools");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemDrawLine.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemDrawLine.setText("Draw Line");
        itemDrawLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDrawLineActionPerformed(evt);
            }
        });
        jMenu4.add(itemDrawLine);

        itemDragObj.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemDragObj.setText("Drag Object");
        itemDragObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDragObjActionPerformed(evt);
            }
        });
        jMenu4.add(itemDragObj);

        radioItemSelect.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        radioItemSelect.setSelected(true);
        radioItemSelect.setText("Select Component");
        radioItemSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemSelectActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemSelect);

        radioItemMove.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        radioItemMove.setText("Move Component");
        radioItemMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemMoveActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemMove);

        radioItemJoin.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        radioItemJoin.setText("Join Components");
        radioItemJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemJoinActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemJoin);

        radioItemAdd.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        radioItemAdd.setText("Add Components");
        radioItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemAddActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemAdd);

        radioItemDelete.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        radioItemDelete.setText("Delete Components");
        radioItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemDeleteActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemDelete);

        radioItemDeleteLine.setText("Delete Connections");
        radioItemDeleteLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioItemDeleteLineActionPerformed(evt);
            }
        });
        jMenu4.add(radioItemDeleteLine);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Source");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        itemGenCode.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemGenCode.setText("Generate Code");
        itemGenCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenCodeActionPerformed(evt);
            }
        });
        jMenu5.add(itemGenCode);

        itemAutoForm.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemAutoForm.setText("Auto Format");
        itemAutoForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutoFormActionPerformed(evt);
            }
        });
        jMenu5.add(itemAutoForm);

        itemCodeSave.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemCodeSave.setText("Save");
        jMenu5.add(itemCodeSave);

        itemCompile.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemCompile.setText("Compile");
        itemCompile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompileActionPerformed(evt);
            }
        });
        jMenu5.add(itemCompile);

        itemRun.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        itemRun.setText("Run");
        itemRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRunActionPerformed(evt);
            }
        });
        jMenu5.add(itemRun);

        itemStop.setText("Stop");
        itemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStopActionPerformed(evt);
            }
        });
        jMenu5.add(itemStop);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incFontSizeActionPerformed
        fontSize+=2;
        setCodeFont();
    }//GEN-LAST:event_incFontSizeActionPerformed

    private void decFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFontSizeActionPerformed
        fontSize-=2;
        setCodeFont();
    }//GEN-LAST:event_decFontSizeActionPerformed

    private void itemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewActionPerformed
        tabCount++;
        NewTab tab=new NewTab();
        fileTabPane.add("Tab "+tabCount,tab);
        tabs.add(tab);
        setCodeFont();
    }//GEN-LAST:event_itemNewActionPerformed

    private void itemDrawLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDrawLineActionPerformed
        dragState=false;
        CanvasPanel.changeState(dragState);
    }//GEN-LAST:event_itemDrawLineActionPerformed

    private void itemDragObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDragObjActionPerformed
        dragState=true;
        CanvasPanel.changeState(dragState);
    }//GEN-LAST:event_itemDragObjActionPerformed

    private void radioItemSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemSelectActionPerformed
        deSelectAll();
        radioItemSelect.setSelected(true);
        setState(true,false);
    }//GEN-LAST:event_radioItemSelectActionPerformed

    private void radioItemMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemMoveActionPerformed
        deSelectAll();
        radioItemMove.setSelected(true);
        setState(true,false);
    }//GEN-LAST:event_radioItemMoveActionPerformed

    private void radioItemJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemJoinActionPerformed
        deSelectAll();
        radioItemJoin.setSelected(true);
        setState(false,false);
    }//GEN-LAST:event_radioItemJoinActionPerformed

    private void radioItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemAddActionPerformed
        deSelectAll();
        radioItemAdd.setSelected(true);
        setState(true,false);
    }//GEN-LAST:event_radioItemAddActionPerformed

    private void radioItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemDeleteActionPerformed
        deSelectAll();
        radioItemDelete.setSelected(true);
        setState(true,true);
    }//GEN-LAST:event_radioItemDeleteActionPerformed

    private void itemGenCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenCodeActionPerformed
        //Shapes start=CanvasPanel
        int curTabIndex=fileTabPane.getSelectedIndex();
        
        NewTab curTab = tabs.get(curTabIndex);
        Shapes start = curTab.canvasPanel1.startNode;
        
        Set<Shapes> visited = new HashSet<>();
        Stack<Shapes> ads = new Stack<>();
        Queue<Shapes> output = new LinkedList<>();
        
        visited.add(start);
        ads.push(start);
        
        while (!ads.isEmpty()) {
            Shapes cur=ads.pop();
            if (cur==null) {
                System.out.println("cur is null");
                
            }
            else {
                for (Shapes neighbor:cur.linkedShapes) {
                    if (!visited.contains(neighbor)) {
                        ads.push(neighbor);
                        visited.add(neighbor);
                    }
                }
                output.add(cur);
            }
            
        }
        
        System.out.println("Generated code : ");
        String code="";
        for (Shapes shape:output) {
            System.out.println(shape.text);
            code=code+shape.text+"\n";
        }
        
        CodeGenerator coder = new CodeGenerator(output);
        ArrayList<String> statements=new ArrayList<>();
        
        //statements = coder.getCCode();
        statements = coder.generateCode(start);

        //System.out.println(statements);
        code="";
        for (String statement:statements) {
            code=code+statement;
        }
        curTab.codeTextArea1.setText(code);
        
    }//GEN-LAST:event_itemGenCodeActionPerformed

    private void itemCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompileActionPerformed
        //CodeCompiler code = new CodeCompiler(this);
        int curTabIndex=fileTabPane.getSelectedIndex();
        NewTab curTab = tabs.get(curTabIndex);
        String dir=tmpDir;
        String file=curTab.tmpFileName;
        
        if (file==null || file.indexOf('.')==-1) {
            saveTempFile();
            file=curTab.tmpFileName;
        }
        else {
            saveTempFile();
        }
        
        if (file.contains(".java")) {
            file=file.substring(0,file.indexOf('.'));
            codeComp.CompileJava(dir,file);
        }
        else if (file.contains(".cpp")){
            file=file.substring(0,file.indexOf('.'));
            codeComp.CompileC(dir, file);
        }
        
        //code.CompileJava("C:\\Users\\Shreyas\\Desktop","Hello");
    }//GEN-LAST:event_itemCompileActionPerformed

    private void itemRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRunActionPerformed
        //CodeCompiler codeComp = new CodeCompiler(this);
        int curTabIndex=fileTabPane.getSelectedIndex();
        NewTab curTab = tabs.get(curTabIndex);
        String dir=tmpDir;
        String file=curTab.tmpFileName;
        
        if (file==null || file.indexOf('.')==-1) {
            ;
        }
        else {
            
            if (file.contains(".java")) {
                file=file.substring(0,file.indexOf('.'));
                codeComp.runProg(dir,file,false);
            }
            else if (file.contains(".cpp")){
                file=file.substring(0,file.indexOf('.'));
                codeComp.runProg(dir,file,true);
            }
        }
        
        //code.runProg("C:\\Users\\Shreyas\\Desktop","Hello",false);
    }//GEN-LAST:event_itemRunActionPerformed

    private void itemAutoFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutoFormActionPerformed
        System.out.println(time().replaceAll(":","_"));
    }//GEN-LAST:event_itemAutoFormActionPerformed

    private void itemSaveAsPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveAsPNGActionPerformed
        takeSnapShot();
    }//GEN-LAST:event_itemSaveAsPNGActionPerformed

    private void radioItemDeleteLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioItemDeleteLineActionPerformed
        deSelectAll();
        radioItemDeleteLine.setSelected(true);
        setState(false,true);
    }//GEN-LAST:event_radioItemDeleteLineActionPerformed

    private void itemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStopActionPerformed
        codeComp.terminateProcess=true;
    }//GEN-LAST:event_itemStopActionPerformed

    public void takeSnapShot() {
       int curTabIndex=fileTabPane.getSelectedIndex();
       NewTab curTab = tabs.get(curTabIndex);
       CanvasPanel panel=curTab.canvasPanel1; 
       BufferedImage bufImage = new BufferedImage(panel.getSize().width, panel.getSize().height,BufferedImage.TYPE_INT_RGB);
       panel.paint(bufImage.createGraphics());
       String imgFile="IMG_"+curTab.tmpFileName;
       if (imgFile==null || imgFile=="") {
           imgFile="IMG_tempImg";
       }
       File imageFile = new File(tmpDir+"\\"+imgFile+".jpeg");
        try{
            imageFile.createNewFile();
            ImageIO.write(bufImage, "jpeg", imageFile);
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    private void deSelectAll() {
        radioItemSelect.setSelected(false);
        radioItemMove.setSelected(false);
        radioItemJoin.setSelected(false);
        radioItemAdd.setSelected(false);
        radioItemDelete.setSelected(false);
        radioItemDeleteLine.setSelected(false);
    }
    
    private void setState(boolean stat1,boolean stat2) {
        dragState=stat1;
        deleteState=stat2;
        CanvasPanel.changeState(dragState);
        CanvasPanel.changeDeleteState(deleteState);
    }
    
    private void setCodeFont() {
        for (NewTab curTab:tabs) {
            curTab.codeTextArea1.setFont(fontSize);
        }
    }
    
    protected void changeSetting() {
        dragState = (!dragState); 
            CanvasPanel.changeState(dragState);
            if(dragState){
                //btnLine.setText("Drag");
            }else{
                //btnLine.setText("Line");
            }
    }
    
    protected void saveTempFile() {
        try
        {
            int curTabIndex=fileTabPane.getSelectedIndex();
            NewTab curTab = tabs.get(curTabIndex);
            curTab.tmpFileName="temp_"+time()+ext;
            file=tmpDir+"\\"+curTab.tmpFileName;
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter p = new PrintWriter(bw);
            String data[]=curTab.codeTextArea1.getText().split("\n");
            for (String data1 : data) {
                p.println(data1);
            }
            p.flush();
            fw.close();
        }
        catch (Exception e)
        {
            System.out.println("Writing error");
        }
    }
    
    private String time() {
        String DATE_FORMAT_NOW="HH:mm dd-MM-yyyy";
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
        String t= sdf.format(cal.getTime());
        t=t.replaceAll(":","_").replaceAll("-","_").replaceAll(" ","_");
        return t;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mwin = new MainWindow();
                mwin.setVisible(true);
                MainFrame = mwin;
            }
        });
    }

    private int fontSize=18;
    private boolean dragState = true;
    private int tabCount=1;
    private ArrayList<NewTab> tabs;
    public static MainWindow MainFrame;
    private static boolean deleteState = false;
    private String dir="",file="";
    private String tmpDir="C:\\Users\\Shreyas\\Desktop\\tempfiles";
    private String ext=".cpp";
    private CodeCompiler codeComp;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem decFontSize;
    public javax.swing.JTabbedPane fileTabPane;
    private javax.swing.JMenuItem incFontSize;
    private javax.swing.JMenuItem itemAutoForm;
    private javax.swing.JMenuItem itemClose;
    private javax.swing.JMenuItem itemCodeSave;
    private javax.swing.JMenuItem itemCompile;
    private javax.swing.JMenuItem itemDragObj;
    private javax.swing.JMenuItem itemDrawLine;
    private javax.swing.JMenuItem itemExportCode;
    private javax.swing.JMenuItem itemGenCode;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JMenuItem itemOpen;
    private javax.swing.JMenuItem itemRun;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemSaveAsPNG;
    private javax.swing.JMenuItem itemStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private Beans.NewTab newTab1;
    public javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButtonMenuItem radioItemAdd;
    private javax.swing.JRadioButtonMenuItem radioItemDelete;
    private javax.swing.JRadioButtonMenuItem radioItemDeleteLine;
    private javax.swing.JRadioButtonMenuItem radioItemJoin;
    private javax.swing.JRadioButtonMenuItem radioItemMove;
    private javax.swing.JRadioButtonMenuItem radioItemSelect;
    private Beans.ToolBar toolBar1;
    // End of variables declaration//GEN-END:variables
}
